set(DISPLAYCLUSTER_REPO_URL https://github.com/kaust-vislab/DisplayCluster.git)
#<<<<<<< HEAD
#set(DISPLAYCLUSTER_CMAKE_ARGS -DBUILD_DISPLAYCLUSTER_LIBRARY=ON -DBUILD_DESKTOPSTREAMER=ON #-DENABLE_TUIO_TOUCH_LISTENER=ON -DENABLE_PDF_SUPPORT=ON -DCMAKE_OSX_ARCHITECTURES=x86_64)
set(DISPLAYCLUSTER_CMAKE_BUILD_TYPE=Release)
set(DISPLAYCLUSTER_ENABLE_PYTHON_SUPPORT=ON)